### ISSUE TITLE
Recommended image size for "full page" cover image?

### ISSUE THREAD

**Issue by ryanwalls** [dencold/hasper#12]
My cover image is 1600 x 1200.  At all resolutions I have tried, the cover image is not taking the full screen.  i.e.  The break is showing.  

The original repo demo page: http://vjeantet.fr, is full screen for me when it first loads.  But when I use his exact image as my cover, it doesn't show up full screen.  Which leads me to believe I need to configure something.  

Any ideas?

And thanks for creating a fork and continuing on with the project.  I'm an experience golang developer, but this is my first foray into Hugo.  Will hopefully be able to contribute back to your theme as I gain more experience.

**Comment by dencold** [comment]
Hey @ryanwalls yes, I recently switched off of the "full screen" implementation because a lot of people missed that there was content below the fold. You can see this in commit c8179586fdcb641ea0caa40657b72d7400abd0e4. 

I'm sorry this affected you! I have been tweaking things mostly for myself and have yet to finalize the theme for public consumption. I haven't yet listed the theme on Hugo, so I'm surprised you even found it at this point :) 

Thanks so much for using Hasper! I'll make this a configurable option next week so that you can resume using it as you expected.

**Comment by ryanwalls** [comment]
@dencold Yeah, I found your version when reading your PR for "authoravatar" on the original repo.  I like using repos that have active authors.  Don't worry about breaking things for me too much.  Move fast and I'll adapt. :)

**Comment by dencold** [comment]
Hey @ryanwalls this is now a configurable option on hasper. There is now a `fullCover` property on the `config.yaml` file. If you set to `true` you'll get the old behavior of the original theme back. This is also the default, so if it is not set, the cover image will take up the full viewport. Setting to `false` gives you the "content peek" that I prefer on my blog.

Update to [v0.0.2](https://github.com/dencold/hasper/releases/tag/v0.0.2) to get this functionality.
